### ISSUE TITLE
[おせち予約] おせち予約データに予約年フィールド追加

### ISSUE THREAD

**Issue by KentaYamada** [KentaYamada/siphon-reservation-manager#312]
## 概要
去年実装しそびれたので、予約年フィールドを追加する。

## Tasks
- [x] back: security rules→new_year_dishes_reservationsに`reservation_year (予約年度)`追加
- [x] back: security rulesユニットテストにフィールド追加対応 (ついでにリファクタ)
- [x] back: new_year_dishes_reservation entityに`reservation_year (予約年度)`追加
- [x] back: firestore converterクラス実装
- [x] back: サービスクラスリファクタ (Converterクラス実装、モジュールパス変更)
- [x] back: サービスクラスユニットテスト実装
- [x] back: store実装
- [x] front: rxjsからvuexへ置換
