### ISSUE TITLE
[おせち予約] 受付フォームに商品購入エリアを追加

### ISSUE THREAD

**Issue by KentaYamada** [KentaYamada/siphon-reservation-manager#313]
## 概要
おせちに使うスイーツの単品販売も受け付けるため、商品購入エリアを追加する。  
対象商品はマスタ管理で設定することとする。  
商品ごとに数量を設定できるようにする。  
数量は上限3つ/商品。  
在庫数は単品商品、おせち共有のため、なくなり次第終了

## Tasks
- [ ] ui: 商品・数量エリア実装
- [ ] back: new_year_dishes_reservationsにitemsサブコレクションを追加 
- [ ] back: 商品データ登録・変更機能実装
- [ ] back: セキュリティルール実装

### Schema
collection_path: new_year_dishes_reservations/items

| Field | Type | Nullable | Key | Memo |
| :--- | :--- | :---: | :--- | :--- |
| id | string | x | PK | マスタのIDをそのままセット|
| name | string | x | | |
| created_at | timestamp | x | | |
| modified_at | timestamp | x | | |
